image: condaforge/mambaforge
tasks:
  - name: Set up Conda channels and environment
    before: |
      conda config --add channels bioconda
      conda config --add channels conda-forge
      conda create -y -n local-env 
      conda activate local-env
      mamba install -y python=3.9
      mamba install -y r pysam samtools=1.15.1 bedtools pysam
      echo "conda activate local-env" >> ~/.bashrc
    command: conda activate local-env

