image:
  file: .gitpod.Dockerfile
tasks:
  - name: Add bioconda channel
    before: |
      conda config --add channels bioconda
vscode:
  extensions:
    - yzhang.markdown-all-in-one
    - ikuyadeu.r
